language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache: yarn

script: yarn test --coverage

after_script:
  - cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage
